"""B3 report: collect the probe, generation, training, end-to-end and fixing results into
results/uc24/b3_results.{md,json}.

    python scripts/uc_b3_report.py
"""
import json
import os

import numpy as np

OUT = os.path.join("results", "uc24")
DATA = os.path.join("data", "generated", "uc24")


def jload(p):
    return json.load(open(p)) if os.path.exists(p) else None


def fmt(rows, cols, names=None):
    names = names or cols
    head = "| " + " | ".join(names) + " |\n|" + "---|" * len(cols) + "\n"

    def f(v):
        if isinstance(v, float):
            if not np.isfinite(v):
                return "–"
            return f"{v:.3f}" if abs(v) < 10 else f"{v:.1f}"
        return str(v)
    return head + "".join("| " + " | ".join(f(r.get(c, "")) for c in cols) + " |\n" for r in rows)


if __name__ == "__main__":
    res, md = {}, ["# B3: 24-hour network-constrained UC (RTS-GMLC, uc24)\n",
                   "Generated by `scripts/uc_b3_report.py`. Method and discussion: `docs/methods/b3.md`.\n"]
    pr = jload(os.path.join(OUT, "b3_probe_T24.json"))
    if pr:
        rows = []
        for r in pr["rows"]:
            g = {k: (v if float(k) <= r["time"] else None) for k, v in r["gap_at"].items()}   # after termination: n/a
            rows.append({"day": r["day"], "time_s": r["time"], "final_gap_%": r["gap"] * 100, "optimal": str(r["opt"]),
                         "gap@60s_%": (g.get("60") or np.nan) * 100, "gap@180s_%": (g.get("180") or np.nan) * 100,
                         "gap@300s_%": (g.get("300") or np.nan) * 100, "gap@600s_%": (g.get("600") or np.nan) * 100,
                         "relax_gap_%": (r["obj"] - r["c_rel"]) / r["obj"] * 100, "incumbents": len(r["inc"])})
        res["probe"] = rows
        md += ["## Probe (full MILP, T = 24, start hour 0, network on, 0.1 % gap, 900 s limit, 1 thread, 2 in parallel)\n",
               fmt(rows, list(rows[0].keys())), ""]
    gen = {s: jload(os.path.join(DATA, f"{s}.json")) for s in ("train", "val", "test")}
    res["generation"] = gen
    if gen["test"]:
        md += ["## Data generation\n"]
        for s, g in gen.items():
            if g:
                md.append(f"- **{s}** ({g['n']} instances, mode {g['cfg']['mode']}, wall {g['wall_s'] / 60:.1f} min): " +
                          ", ".join(f"{k} {v:.3f}" if isinstance(v, float) else f"{k} {v}" for k, v in g.items()
                                    if k not in ("cfg", "n", "wall_s")))
        md.append("")
    if os.path.exists(os.path.join(DATA, "test.npz")):
        te = dict(np.load(os.path.join(DATA, "test.npz")))
        rows = []
        for i in range(len(te["obj"])):
            tt, oo = te["inc_t"][i], te["inc_obj"][i]
            ok = np.isfinite(tt)
            r = {"time_s": float(te["time"][i]), "cpu_s": float(te["cpu"][i]), "gap_%": float(te["gap"][i] * 100),
                 "optimal": bool(te["opt"][i])}
            for q in (0.5, 0.1, 0.0):
                hit = np.where(ok & (oo <= te["obj"][i] * (1 + q / 100) + 1e-9))[0]
                r[f"t_within_{q}"] = float(tt[hit[0]]) if len(hit) else np.nan
            rows.append(r)
        A = lambda k: np.array([r[k] for r in rows], float)
        char = {"n": len(rows), "time_mean_s": float(A("time_s").mean()), "time_median_s": float(np.median(A("time_s"))),
                "time_min_s": float(A("time_s").min()), "cpu_mean_s": float(A("cpu_s").mean()),
                "hit_limit_%": float(100 - A("optimal").mean() * 100), "final_gap_mean_%": float(A("gap_%").mean()),
                "final_gap_max_%": float(A("gap_%").max()),
                "t_within_0.5%_of_final_median_s": float(np.nanmedian(A("t_within_0.5"))),
                "t_within_0.1%_of_final_median_s": float(np.nanmedian(A("t_within_0.1"))),
                "t_final_incumbent_median_s": float(np.nanmedian(A("t_within_0.0"))),
                "t_within_0.1%_of_final_mean_s": float(np.nanmean(A("t_within_0.1"))),
                "served_%": float(((te["shed"] < 1e-6) & (te["short"] < 1e-6)).mean() * 100),
                "loadavg_mean": float(te["loadavg"].mean())}
        res["full_milp_test"] = char
        md += ["## Full MILP on the test set (300 s, 0.1 %)\n",
               ", ".join(f"{k} {v:.3g}" if isinstance(v, float) else f"{k} {v}" for k, v in char.items()), ""]
    tr = jload(os.path.join(OUT, "b3_train.json"))
    if tr:
        res["training"] = {k: v for k, v in tr.items() if k != "rl_hist"}
        md += ["## Training (no full MILP)\n",
               f"- labels: LP relaxation + repairs, {tr.get('label_s_mean', np.nan):.2f} s per instance "
               f"(relaxation {tr.get('relax_s_mean', np.nan):.2f} s)",
               f"- LF-BCE: {tr.get('lf_bce_train_s', np.nan) / 60:.1f} min; REINFORCE: {tr.get('rl_train_s', np.nan) / 60:.1f} min, "
               f"{tr.get('rl_LPs', 0)} dispatch LPs; selected checkpoint step {tr.get('rl_selected_step')}",
               f"- decoding thresholds chosen on val: " +
               ", ".join(f"{k} {v['threshold']}" for k, v in tr.get("thresholds", {}).items()), ""]
        ck = tr.get("rl_ckpts", {})
        if ck:
            rows = [{"step": 0, **{f"block {k}": v for k, v in tr["rl_ckpt0"]["block"].items() if k != "method"}}] + \
                   [{"step": int(s), **{f"block {k}": v for k, v in c["block"].items() if k != "method"}} for s, c in ck.items()]
            md += ["Validation of REINFORCE checkpoints (top-1 + block repair -> LP):\n", fmt(rows, list(rows[0].keys())), ""]
    e2e = jload(os.path.join(OUT, "b3_e2e_results.json"))
    if e2e:
        res["end_to_end"] = e2e["rows"]
        cols = ["method", "no_shed_no_shortfall_%", "gap_median_%", "gap_mean_served_%", "gap_mean_%", "units_on",
                "LPs_per_instance"]
        md += ["## End-to-end (test): one LP (or screening), no MILP\n",
               fmt(e2e["rows"], cols, ["method", "served %", "median gap %", "mean gap, served %", "mean gap %",
                                        "units on", "LPs / inst."]), ""]
    sel = jload(os.path.join(OUT, "b3_fix_select.json"))
    if sel:
        res["fix_select"] = sel
        cols = ["method", "n", "fixed_share_%", "gap_mean_%", "gap_median_%", "gap_max_%", "served_%", "speedup_mean_x",
                "limit_hit_%"]
        md += [f"## Fixing: selection on val ({sel['rule']}): {sel['best']}\n", fmt(sel["val_rows"], cols), ""]
    fx = jload(os.path.join(OUT, "b3_fix_test.json"))
    if fx:
        res["fix_test"] = fx
        cols = ["method", "n", "fixed_share_%", "gap_mean_%", "gap_median_%", "gap_p90_%", "gap_max_%", "served_%",
                "time_mean_s", "speedup_mean_x", "speedup_median_x", "cpu_speedup_mean_x", "ttq_reached_%",
                "ttq_speedup_median_x", "limit_hit_%", "fallback_%"]
        names = ["method", "n", "fixed %", "mean gap %", "median gap %", "p90 gap %", "max gap %", "served %",
                 "time s", "speed-up (mean times)", "speed-up (median)", "CPU speed-up", "full reaches cost %",
                 "TTQ speed-up (median)", "limit hit %", "fallback %"]
        md += ["## Solver acceleration (test): partial fixing + reduced MILP vs the full MILP\n",
               "Speed-up = full-MILP time (generation run) / pipeline time (LP relaxation for features + guard LPs + "
               "reduced MILP). TTQ = time the full MILP's incumbent log needs to reach the reduced solution's cost "
               "(censored at the full MILP's time when never reached).\n",
               fmt(fx["rows"], cols, names), ""]
        fx2 = jload(os.path.join(OUT, "b3_fix_test_extra.json"))
        if fx2:
            res["fix_test_extra"] = fx2
            md += ["Additional rankings (not selected on val; reported for the speed / quality frontier):\n",
                   fmt(fx2["rows"], cols, names), ""]
        if fx.get("rows_b2b"):
            b = fx["b2b"]
            md += [f"Back-to-back subset ({b['n']} instances; full MILP re-solved in the same worker, mean "
                   f"{b['full_time_b2b_mean']:.0f} s vs {b['full_time_gen_mean']:.0f} s in generation):\n",
                   fmt(fx["rows_b2b"], cols, names), ""]
    jl = os.path.join(OUT, "b3_fix_test.jsonl")
    if os.path.exists(jl) and os.path.exists(os.path.join(DATA, "test.npz")):
        # anytime comparison: time to a solution within q % of the full MILP's final cost (reference), for the full
        # MILP (its incumbent log) and for each fixing pipeline (LP relaxation + guards + the reduced MILP's log)
        te = dict(np.load(os.path.join(DATA, "test.npz")))
        rs = [json.loads(x) for x in open(jl)]
        jl2 = os.path.join(OUT, "b3_fix_test_extra.jsonl")
        if os.path.exists(jl2):                     # merge the extra rankings of the same instances
            ex = {r["i"]: r for r in (json.loads(x) for x in open(jl2))}
            rs = [dict(r, **{k: v for k, v in ex[r["i"]].items() if "|" in k}) for r in rs if r["i"] in ex] \
                if len(ex) == len(rs) else rs
        names = [k for k in rs[0] if "|" in k]
        rows = []
        for q in (0.5, 0.25, 0.1):
            for nm in names:
                tf, tr_, ok = [], [], []
                for r in rs:
                    i = r["i"]
                    ref = te["obj"][i] * (1 + q / 100) + 1e-9
                    tt, oo = te["inc_t"][i], te["inc_obj"][i]
                    hit = np.where(np.isfinite(tt) & (oo <= ref))[0]
                    t_full = float(tt[hit[0]]) if len(hit) else np.nan
                    R = r[nm]
                    inc = [x for x in R.get("inc", []) if x[1] <= ref]
                    over = te["t_rel"][i] + R["t_guard"]
                    t_red = over + inc[0][0] if (inc and not R["fallback"]) else np.nan
                    tf.append(t_full); tr_.append(t_red); ok.append(np.isfinite(t_red))
                tf, tr_, ok = np.array(tf), np.array(tr_), np.array(ok)
                both = ok & np.isfinite(tf)
                rows.append({"target": f"within {q} % of full MILP cost", "method": nm, "n": len(rs),
                             "reduced_reaches_%": float(ok.mean() * 100),
                             "full_time_to_target_median_s": float(np.nanmedian(tf)),
                             "reduced_time_to_target_median_s": float(np.nanmedian(tr_)) if ok.any() else np.nan,
                             "speedup_median_x (both reach)": float(np.median(tf[both] / tr_[both])) if both.any() else np.nan,
                             "speedup_mean_times_x (both reach)": float(tf[both].mean() / tr_[both].mean()) if both.any() else np.nan})
        res["anytime"] = rows
        md += ["## Anytime comparison (test): time to a solution within q % of the full MILP's final cost\n",
               "Full MILP: first incumbent below the target. Fixing pipeline: LP relaxation + guards + first incumbent of "
               "the reduced MILP below the target (instances where the reduced MILP never reaches the target count as "
               "failures in 'reduced reaches').\n",
               fmt(rows, list(rows[0].keys())), ""]
    open(os.path.join(OUT, "b3_results.md"), "w").write("\n".join(md) + "\n")
    json.dump(res, open(os.path.join(OUT, "b3_results.json"), "w"), indent=1, default=float)
    print("\n".join(md))
