"""Assemble results/uc12/constrained_results.{md,json} from the val / test outputs of uc_constrained.py.

    python scripts/uc_constrained_report.py --test_tag final
"""
import argparse
import glob
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from otsl.ucdata import load  # noqa: E402

OUT = os.path.join("results", "uc12")
COLS = [("method", "method"), ("no_shed_no_shortfall_%", "served %"), ("gap_median_%", "median gap %"),
        ("gap_mean_served_%", "mean gap, served %"), ("gap_mean_%", "mean gap %"), ("units_on", "units on"),
        ("LPs_per_instance", "LPs / inst.")]


def table(rows, cols=COLS, extra=()):
    cols = list(cols) + list(extra)
    out = "| " + " | ".join(c[1] for c in cols) + " |\n|" + "---|" * len(cols) + "\n"
    for r in rows:
        cells = []
        for k, _ in cols:
            v = r.get(k, "")
            if isinstance(v, float):
                cells.append("nan" if np.isnan(v) else (f"{v:.1f}" if k in ("no_shed_no_shortfall_%",) else
                                                         f"{v:.2f}" if abs(v) < 1000 else f"{v:.0f}"))
            else:
                cells.append(str(v))
        out += "| " + " | ".join(cells) + " |\n"
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--test_tag", default="final")
    ap.add_argument("--proposed", default="")
    ap.add_argument("--pairs", default="", help="a:b,c:d  paired comparisons of top-1 rows (test)")
    a = ap.parse_args()
    te = load(os.path.join("data", "generated", "uc12", "test.npz"))
    res = {"val": {}, "test": None}
    md = "# Constrained fine-tuning of Model 1 for the end-to-end mode (B2, uc12)\n\n"
    md += "Generated by `scripts/uc_constrained_report.py` from `results/uc12/constrained_val_*.json` and " \
          f"`constrained_test_{a.test_tag}.json`. Gaps are relative to the MILP reference (60 s, 0.1 %); " \
          "'served' = no load shedding / spill and no reserve shortfall in the exact dispatch LP.\n\n"

    # ------------------------------------------------------------------ test
    tp = os.path.join(OUT, f"constrained_test_{a.test_tag}.json")
    if os.path.exists(tp):
        rows = json.load(open(tp))["rows"]
        res["test"] = rows
        md += "## Test (all 120 instances)\n\n" + table(rows) + "\n"
        arr_p = os.path.join(OUT, f"constrained_test_{a.test_tag}_arrays.npz")
        if os.path.exists(arr_p) and a.pairs:
            arr = np.load(arr_p)
            names = list(arr["names"])
            md += "### Paired comparisons (test, same instances)\n\n"
            md += "| A | B | served by both | mean gap A on both % | mean gap B on both % | A cheaper (of both) | served A only | served B only |\n|---|---|---|---|---|---|---|---|\n"
            res["pairs"] = []
            for pr in a.pairs.split(","):
                x, y = pr.split(":")
                fx = [n for n in names if n.startswith(x + ": top-1 -> LP") or n == x]
                fy = [n for n in names if n.startswith(y + ": top-1 -> LP") or n == y]
                if not fx or not fy:
                    continue
                A, B = arr[fx[0].replace("/", "_")], arr[fy[0].replace("/", "_")]
                sa = (A[1] < 1e-6) & (A[2] < 1e-6)
                sb = (B[1] < 1e-6) & (B[2] < 1e-6)
                both = sa & sb
                ga = (A[0] - te["obj"]) / te["obj"] * 100
                gb = (B[0] - te["obj"]) / te["obj"] * 100
                p = {"A": fx[0], "B": fy[0], "both": int(both.sum()), "gapA": float(ga[both].mean()),
                     "gapB": float(gb[both].mean()), "A_cheaper": int((A[0][both] < B[0][both] - 1e-6).sum()),
                     "A_only": int((sa & ~sb).sum()), "B_only": int((sb & ~sa).sum())}
                res["pairs"].append(p)
                md += f"| {fx[0]} | {fy[0]} | {p['both']} | {p['gapA']:.2f} | {p['gapB']:.2f} | {p['A_cheaper']} | {p['A_only']} | {p['B_only']} |\n"
            md += "\n"

    # ------------------------------------------------------------------ val
    vrows, runs = [], []
    for f in sorted(glob.glob(os.path.join(OUT, "constrained_val_*.json"))):
        name = os.path.basename(f)[len("constrained_val_"):-5]
        j = json.load(open(f))
        res["val"][name] = {k: v for k, v in j.items() if k != "hist"}
        vrows += j["rows"]
        if "hist" in j:
            h = j["hist"]
            if h and not isinstance(h[0], dict):      # otsl.ucml.train_uc_reinforce: list of sampled gaps
                h = [{"step": i, "sampled_gap": x} for i, x in enumerate(h)]
            last = h[-20:]
            run = {"run": name, "hp": j.get("hp"), "train_s": j.get("train_s"), "train_LPs": j.get("train_LPs"),
                   "val_curve": [dict({"step": x["step"] + 1}, **x["val"]) for x in h if "val" in x]}
            if "lam" in h[0]:
                run.update(lam_final=h[-1]["lam"], viol_greedy_last20=float(np.mean([x["viol_greedy"] for x in last])),
                           viol_sample_last20=float(np.mean([x["viol_sample"] for x in last])),
                           units_greedy_last20=float(np.mean([x["units_on_greedy"] for x in last])))
            runs.append(run)
            res["val"][name]["summary"] = run
    md += "## Validation (60 instances; hyperparameter / variant selection)\n\n"
    md += table(vrows, extra=[("gap_to_relax_mean_served_%", "gap to LP relaxation, served %")]) + "\n"
    md += "## Training runs\n\n| run | hyperparameters | train time s | training LPs | final lambda | deployed violation, last 20 steps | units on (deployed), last 20 |\n|---|---|---|---|---|---|---|\n"
    for r in runs:
        md += f"| {r['run']} | {json.dumps(r['hp'])} | {r['train_s']:.0f} | {r['train_LPs']} | " \
              f"{r.get('lam_final', float('nan')):.3g} | {r.get('viol_greedy_last20', float('nan')):.3f} | " \
              f"{r.get('units_greedy_last20', float('nan')):.2f} |\n"
    md += "\n### Validation checkpoints (deployed decoder; label-free numbers: gap to the LP relaxation)\n\n"
    md += "| run | step | served % | gap to relaxation, served % | mean cost / relaxation | units on |\n|---|---|---|---|---|---|\n"
    for r in runs:
        for v in r["val_curve"]:
            md += f"| {r['run']} | {v.get('step', '')} | {v['served_%']:.1f} | {v['gap_to_relax_served_%']:.2f} | " \
                  f"{v.get('mean_cost_over_relax', float('nan')):.3f} | {v['units_on']:.2f} |\n"
    cal_p = os.path.join(OUT, "constrained_calib.json")
    if os.path.exists(cal_p):
        cal = json.load(open(cal_p))
        res["calibration"] = cal
        md += "\n### Decision threshold calibrated on val (minimum mean LP cost / relaxation cost)\n\n| model | decoder | threshold |\n|---|---|---|\n"
        for k, v in cal.items():
            for dec, x in v.items():
                md += f"| {k} | {dec} | {x['threshold']} |\n"
    with open(os.path.join(OUT, "constrained_results.md"), "w") as f:
        f.write(md)
    with open(os.path.join(OUT, "constrained_results.json"), "w") as f:
        json.dump(res, f, indent=1, default=float)
    print(md)
