"""Tables for the self-training study: results/uc12/selftrain_results.md and .json from selftrain_state.json.

    python scripts/uc_selftrain_report.py
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from run_model1 import fmt_table  # noqa: E402

if __name__ == "__main__":
    os.chdir(os.path.dirname(HERE))
    tag = sys.argv[1] if len(sys.argv) > 1 else ""
    P = lambda name: os.path.join("results", "uc12", f"selftrain{tag}_{name}")
    S = json.load(open(P("state.json")))
    md = ["# Self-training with the solver as teacher (B2, uc12)", "",
          "Generated by `scripts/uc_selftrain_report.py` from `selftrain_state.json` (run: `scripts/uc_selftrain.py`).", ""]

    # ------------------------------------------------------------------ labels
    md += ["## 1. Label pool (500 training instances)", "",
           "Gap columns marked *diag* use the training MILP objective as a diagnostic only (never for training or selection).", ""]
    rows = []
    lab = S.get("labels", {})
    if "round0" in lab:
        rows.append(dict(lab["round0"], stage="round 0: repaired LP relaxation"))
    for r in S.get("rounds", []):
        rows.append(dict(r["pool_after"], stage=f"after round {r['round']}"))
    cols = ["stage", "served_%", "gap_to_LP_bound_median_%", "gap_to_LP_bound_mean_%", "diag_gap_to_MILP_median_%",
            "diag_gap_to_MILP_mean_%", "diag_gap_to_MILP_mean_served_%", "diag_label_le_MILP_%", "units_on", "diag_MILP_units_on"]
    md += [fmt_table(rows, cols), ""]

    if "pilot" in S:
        pr = []
        for q in ("0.8", "0.9"):
            x = S["pilot"][q]
            pr.append(dict(x["labels_after"], q=q, milp_s_mean=x["milp_s_mean"], hit_time_limit_=x["hit_time_limit_%"],
                           accepted_=x["accepted_%"]))
        pr.insert(0, dict(S["pilot"]["before"], q="before (round-0 labels)"))
        md += [f"**Pilot** ({S['pilot']['before']['n']} training instances, round-0 model; chosen q = {S['pilot']['chosen_q']}):", "",
               fmt_table(pr, ["q", "accepted_", "milp_s_mean", "hit_time_limit_", "served_%", "gap_to_LP_bound_median_%",
                              "diag_gap_to_MILP_median_%", "diag_gap_to_MILP_mean_%", "diag_label_le_MILP_%"]), ""]
    if S.get("rounds"):
        rr = []
        for r in S["rounds"]:
            rr.append({"round": r["round"], "q": r["q"], "solved": r["n_solved"], "accepted_%": r["accepted_%"],
                       "milp_s_mean": r["milp_s_mean"], "hit_limit_%": r["hit_time_limit_%"],
                       "chunk served before": r["chunk_before"]["served_%"], "chunk served after": r["chunk_after"]["served_%"],
                       "chunk diag median gap before": r["chunk_before"]["diag_gap_to_MILP_median_%"],
                       "chunk diag median gap after": r["chunk_after"]["diag_gap_to_MILP_median_%"],
                       "chunk diag mean gap after": r["chunk_after"]["diag_gap_to_MILP_mean_%"],
                       "chunk label <= MILP after %": r["chunk_after"]["diag_label_le_MILP_%"],
                       "retrain_s": r.get("train_s"), "round wall_s": r.get("wall_s")})
        md += ["**Rounds** (each relabels one third of the training set with the previous round's model):", "",
               fmt_table(rr, list(rr[0].keys())), ""]

    # ------------------------------------------------------------------ label cost
    lc = S.get("label_cost", {})
    if lc:
        milp_lab = sum(r["milp_core_s"] for r in S.get("rounds", []))
        lp_lab = sum(r["lp_core_s"] for r in S.get("rounds", []))
        pilot = S.get("pilot_core_s", 0.0)
        tot = lc["lp_relaxation_core_s"] + lc["score_lp_core_s_round0"] + milp_lab + lp_lab + pilot
        cost = {"LP relaxations (500, also model inputs)": lc["lp_relaxation_core_s"],
                "dispatch LPs scoring the round-0 labels": lc["score_lp_core_s_round0"],
                "pilot reduced MILPs + LPs (2 settings)": pilot,
                "round reduced MILPs": milp_lab, "round dispatch LPs": lp_lab,
                "TOTAL self-training labels": tot,
                "500 full-MILP labels (data generation)": lc["full_milp_label_core_s"]}
        md += ["## 2. Label cost (solver core-seconds)", "", "| item | core-s | core-h |", "|---|---|---|"]
        md += [f"| {k} | {v:,.0f} | {v / 3600:.2f} |" for k, v in cost.items()]
        md += ["", f"Self-training labels cost **{tot / lc['full_milp_label_core_s'] * 100:.1f} %** of the full-MILP labels "
                   f"({lc['full_milp_label_core_s'] / tot:.1f}x cheaper). Training-time LPs of REINFORCE are not label cost and are "
                   f"listed separately: {S.get('rl_LPs_total', 'n/a')} dispatch LPs in total over all REINFORCE runs of this study.", ""]
        S["label_cost_summary"] = cost

    # ------------------------------------------------------------------ validation
    if S.get("val"):
        vr = []
        for name, v in S["val"].items():
            vr.append({"model": name, "top-1 served %": v["top-1"]["no_shed_no_shortfall_%"],
                       "top-1 median gap to LP bound %": v["top-1"]["gap_median_%"],
                       "adequacy served %": v["adequacy"]["no_shed_no_shortfall_%"],
                       "adequacy median gap to LP bound %": v["adequacy"]["gap_median_%"],
                       "adequacy mean gap served %": v["adequacy"]["gap_mean_served_%"],
                       "units on": v["adequacy"]["units_on"]})
        md += ["## 3. Validation (60 instances; no MILP information: gaps to the LP-relaxation bound)", "",
               fmt_table(vr, list(vr[0].keys())), ""]

    # ------------------------------------------------------------------ test, LP decoders
    if S.get("test_rows"):
        tr = S["test_rows"]
        for r in tr:
            r["excess_units_vs_MILP"] = r.get("units_on", np.nan) - r.get("MILP_units_on", np.nan)
        md += ["## 4. Test, Model 1 -> LP (120 instances; gap to the test MILP, which serves 92.5 % and commits "
               f"{tr[0].get('MILP_units_on', float('nan')):.2f} units per hour on average)", "",
               fmt_table(tr, ["method", "no_shed_no_shortfall_%", "gap_median_%", "gap_mean_served_%", "gap_mean_%",
                              "units_on", "excess_units_vs_MILP", "unit_hour_accuracy_%", "LPs_per_instance"]),
               "Screening of the four baselines was skipped in the final run (time budget after a container restart); their "
               "screening rows are in `uc_label_free_results.md` (same decoder, another random draw of sampled candidates).", ""]

    # ------------------------------------------------------------------ test, fixing
    if S.get("fix_rows"):
        fr = S["fix_rows"]
        md += [f"## 5. Test, fixing + reduced MILP (first {S.get('fix_n', 60)} test instances, full MILP solved back to back in the same "
               f"process; 2 worker processes on a shared machine; wall {S.get('fix_wall_s', 0) / 60:.0f} min)", "",
               fmt_table(fr, ["method", "fixed_share_", "gap_mean_%", "gap_median_%", "no_shed_no_shortfall_%",
                              "matches_or_beats_milp_%", "time_s", "speedup_x", "speedup_median_x", "units_on",
                              "fallback_", "hit_time_limit_"]), ""]

    md += ["## Training times (s)", "", "```", json.dumps(S.get("train_s", {}), indent=1), "```", ""]
    open(P("results.md"), "w").write("\n".join(md))
    out = {k: S.get(k) for k in ("label_cost", "label_cost_summary", "labels", "pilot", "q", "rounds", "val", "test_rows",
                                 "fix_rows", "fix_n", "train_s", "rl_LPs_total", "fix_wall_s")}
    json.dump(out, open(P("results.json"), "w"), indent=1, default=float)
    print("\n".join(md))
